# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sds.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsds.proto\x12\x18io.github.slackhappy.sds\")\n\nGetRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x0c\n\x04keys\x18\x02 \x03(\t\"\x7f\n\x0bGetResponse\x12\x41\n\x06values\x18\x01 \x03(\x0b\x32\x31.io.github.slackhappy.sds.GetResponse.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32u\n\x11StaticDataService\x12`\n\x0fGetValuesSingle\x12$.io.github.slackhappy.sds.GetRequest\x1a%.io.github.slackhappy.sds.GetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sds_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRESPONSE_VALUESENTRY']._loaded_options = None
  _globals['_GETRESPONSE_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_GETREQUEST']._serialized_start=39
  _globals['_GETREQUEST']._serialized_end=80
  _globals['_GETRESPONSE']._serialized_start=82
  _globals['_GETRESPONSE']._serialized_end=209
  _globals['_GETRESPONSE_VALUESENTRY']._serialized_start=164
  _globals['_GETRESPONSE_VALUESENTRY']._serialized_end=209
  _globals['_STATICDATASERVICE']._serialized_start=211
  _globals['_STATICDATASERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
